---
- name: Install nginx dependencies
  ansible.builtin.apt:
    name:
      - libgd-dev
      - libgeoip-dev
      - libkrb5-dev
      - libpcre3-dev
      - libperl-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
    state: present

- name: Install nginx dependencies
  ansible.builtin.apt:
    name:
      - nginx
    state: present
